name: "Karaoke Forever for HA"
version: "23"
slug: karaokeforeverHA
description: >-
  "Home Assistant version of Karaoke Forever"
arch: [amd64, aarch64, armv7, i386]
init: false
startup: services
host_network: true
homeassistant_api: true
video: false
audio: false
ingress: true
ingress_port: 80
options:
  image: "radrootllc/karaoke-eternal/v1.0.0:latest" # Default image to pull
  ports:
    8080/tcp: 8080 # Example port mapping
