build_from:
  amd64: "docker.io/alexxit/go2rtc:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Home Assistant Karaoke Forever DVP"
  org.opencontainers.image.description: "Allows Karaoke Forever on Home Assistant"
  org.opencontainers.image.source: "https://github.com/dvp-coms/karaokeforeverHA"
  org.opencontainers.image.licenses: "Apache License 2.0"