name: "Karaoke Forever for HA"
version: "1"
slug: karaokeforeverHA
description: >-
  "Home Assistant version of Karaoke Forever"
arch: amd64
init: false
startup: services
host_network: true
homeassistant_api: true
video: false
audio: false
ingress: true
ingress_port: 3000
ports:
  3000/tcp: 3000
